### PR TITLE
Support Pre-Commit CI

### PR DESCRIPTION
**Pull request by Archmonger**
Jazzband org has added pre-commit CI as a requirement.

Using the [file suggested by Andrew Chen Wang](https://github.com/orgs/jazzband/teams/members/discussions/18?from_comment=2#discussion-18-comment-2), we are adding a pre-commit CI configuration file.

### Actions performed by CI
- Strip unnecessary `# noqa`s
- isort
- Check for merge conflicts
- black
- Fix End of Files
- Fix requirements.txt
- Trim Trailing Whitespace
- File Contents Sorter
- Check for case conflicts
- Check JSON
- Check Xml
- Check Toml
- Check Xml
- Check Yaml
- Debug Statements (Python)
- Check for added large files
- Check for broken symlinks
- Debug Statements (Python)
- Detect AWS Credentials
- Detect Private Key
- pyupgrade
- flake8
- Check .rst files with the same linter used by pypi.org

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
merging this massive PR as is will break git bisect. so please just add the config files. others will be incrementally fixed by smaller contributions when made. also we don;t need to switch to "" from ' ' right now.

**Comment by Archmonger** [comment]
Since this repo didn't have any workflows for formatting/styling, I would argue this is just paying for the sins of the past. All styling changes in this PR were automated by `black`.

I'd personally say if the changes need to eventually occur, may as well get them out of the way sooner rather than later.

**Comment by Archmonger** [comment]
After removing black, although total LOCs changed has been reduced, this PR is still relatively massive in terms of total files changed due to `pyupgrade`. 

A lot of the changes made by pyupgrade are actually really good IMO. What is your thoughts?

**Comment by auvipy** [comment]
pyupgrade changes should be hanndled in a separate PR.

**Comment by Archmonger** [comment]
Looks like some stuff broke through the revert (merge resolution). Rather than debugging I've created #507

**Pull request closed without merging**
