### PR TITLE
Mask sensitive data

### PR DESCRIPTION
**Pull request by egichuri**
Potential fix for the issue https://github.com/jazzband/django-silk/issues/305

### CODE REVIEW

**Comment by egichuri** [comment]
@avelis mind having a look?

**Comment by avelis** [comment]
@egichuri Merged! Thanks again for contributing!

**Comment by egichuri** [comment]
@avelis could we have a new tag/release?

**Comment by avelis** [comment]
@egichuri Not against making one. Just haven't had time.

**Comment by jscaux** [comment]
Here is another vote for a new tag/release with this bug fix included. Such a serious issue would really benefit from a bit of TLC.

**Pull request merged**
