### PR TITLE
Gracefully error out when there are concurrent profilers

### LINKED ISSUE #682: [Python 3.12] ValueError: Another profiling tool is already active
In python 3.12 sometimes this exception raises, usually immediately after the server starts in the first request.
`SILKY_PYTHON_PROFILER = False` seems to fix it.
```
File "/backend/python/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
  response = get_response(request)

File "/backend/python/lib/python3.12/site-packages/silk/middleware.py", line 70, in __call__
  self.process_request(request)

File "/backend/python/lib/python3.12/site-packages/silk/middleware.py", line 121, in process_request
  DataCollector().configure(request_model, should_profile=should_profile)

File "/backend/python/lib/python3.12/site-packages/silk/collector.py", line 95, in configure
  self.local.pythonprofiler.enable()
ValueError: Another profiling tool is already active
```

https://github.com/python/cpython/issues/110770#issuecomment-1759986100

### PR DESCRIPTION
**Pull request by albertyw**
Fixes #682 
Unblocks #686

### CODE REVIEW

**Review by 50-Course — COMMENTED** [review]
Hello again @albertyw,

this patch permanently fixes the `Django==5.1` & `python^=3.12` pipeline issue?

**Review by 50-Course — APPROVED** [review]
Update: Great progress! The "Gracefully error out when there are concurrent profilers" job (#722) is now passing, which has also unblocked #686.

**Comment by robinchow** [comment]
I'd like to point out while this stop silk from interfering with processing a request, it also ends up *not profiling* that particular request. Prior to Python 3.11, the effect was similar but different (it would disable/stop the first profiler, and then start this current one). Neither outcome seems great, especially since this problem will happen when Django is processing multiple long-running requests at the same time (I've made a minimal repo [here](https://github.com/robinchow/django-silk-multithread.git) to highlight this issue)

I think at a minimum, the documentation should tell users that this issue exists. In terms of a proper fix, I'm not sure at the moment if that's possible without using another profiler that properly supports multithreaded applications (such as https://github.com/sumerc/yappi)

**Comment by 50-Course** [comment]
Thank you for pointing out this oversight, @robinchow. I'd take a look into [yappi](https://github.com/sumerc/yappi)

**Comment by albertyw** [comment]
> Prior to Python 3.11, the effect was similar but different (it would disable/stop the first profiler, and then start this current one)

3.11 or 3.12?  This code gives an error in python 3.12 but no error in 3.11:

```python
import cProfile
p1 = cProfile.Profile()
p1.enable()
p2 = cProfile.Profile()
p2.enable()
```

**Comment by robinchow** [comment]
@albertyw ah yes, apologies, prior to Python 3.12.

**Pull request merged**
