### PR TITLE
Replace url with path for Django 4.0

### PR DESCRIPTION
**Pull request by MuslimBeibytuly**

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
why not use path()?

**Comment by MuslimBeibytuly** [comment]
> why not use path()?

replaced using path, pls review:)

**Review by auvipy — COMMENTED** [review]
do we need to explicitly mention route='' , views= in the path() ?
https://docs.djangoproject.com/en/3.1/ref/urls/

though it looks nice

**Comment by MuslimBeibytuly** [comment]
> do we need to explicitly mention route='' , views= in the path() ?
> https://docs.djangoproject.com/en/3.1/ref/urls/
> 
> though it looks nice
it isn't required, but subjectively transparent keyword args seems to be better:)

**Review by auvipy — APPROVED** [review]

**Comment by MuslimBeibytuly** [comment]
@auvipy when should I be expecting it merged and released?:)

**Comment by auvipy** [comment]
one question, did you try this approach locally?

**Comment by MuslimBeibytuly** [comment]
> one question, did you try this approach locally?

I've ran tests, if that's what you're asking about:)

**Pull request merged**
