### PR TITLE
Use path instead of direct reference for custom intercept logic.

### PR DESCRIPTION
**Pull request by kkaehler**
This is the same way the debug toolbar handles this.

### CODE REVIEW

**Comment by mtford90** [comment]
@kkaehler 

Why not allow both formats? :D

Also - looks like the tests are failing - looks like a syntax error. I don't think you can use `return` within `lambda` expressions - I'm surprised it's working for you?

**Comment by kkaehler** [comment]
Yeah...I screwed up that commit.

I cleaned it up and now it supports both methods. Let me know your thoughts.

**Comment by avelis** [comment]
@kkaehler This looks like a useful addition to this project. I can definitely see the utility for this customization.

It's currently under conflict. If you could resolve it I can take a long and merge it into the master branch.

**Comment by auvipy** [comment]
@avelis do you want me to give this a try on my fork and a pr for review?

**Comment by avelis** [comment]
@auvipy You are always welcome to try out a PR with that keeps with the spirit of this feature.

**Comment by mbeacom** [comment]
Closing this due to inactivity.  Feel free to re-open/re-pr this if relevant.

**Pull request closed without merging**
