### PR TITLE
traceback only when needed

### PR DESCRIPTION
**Pull request by ilndinesh**
calculate traceback only if we need to wrap sql

### CODE REVIEW

**Comment by ilndinesh** [comment]
looks like not update to tests are needed for this

**Comment by auvipy** [comment]
can you check here https://github.com/jazzband/django-silk/blob/master/project/tests/test_view_sql_detail.py and related files?

**Comment by Archmonger** [comment]
@ilndinesh Can you rebase this to the latest django-silk:master

**Comment by SebCorbin** [comment]
This can be considered as code cleanup/performance optimization and could be merged as is (provided the tests pass)

**Review by Archmonger — APPROVED** [review]

**Pull request merged**
