### PR TITLE
Added support of Oracle

### PR DESCRIPTION
**Pull request by pikhovkin**
Added support of Oracle

### CODE REVIEW

**Comment by avelis** [comment]
@pikhovkin I appreciate the effort to add Oracle support for django-silk. I see 2 PR's open. Is there a reason for that? Should those be discarded and this one be the only one for consideration to merge in?

**Comment by pikhovkin** [comment]
You can remove 2 others PR's.

**Comment by albertyw** [comment]
It seems the tests are failing.  Can you fix them?

Also, does travis support oracle as a DB?  If it does, it would be nice to add to `.travis.yml` to ensure compatibility.

**Comment by pikhovkin** [comment]
We must get rid of the UUID fields, because Oracle backend interprets them in SQL as a number, because of this an error occurs.

**Comment by pikhovkin** [comment]
@albertyw I have not worked yet with travis or other like system.

**Comment by pikhovkin** [comment]
@albertyw, please, look erroneous tests https://travis-ci.org/jazzband/django-silk/builds/329821906

**Comment by Archmonger** [comment]
@pikhovkin This PR needs a rebase to the latest django-silk:master, can you work this?

**Review by auvipy — CHANGES_REQUESTED** [review]
we moved to github actions, the tests needed to pass

**Comment by SebCorbin** [comment]
Well, I messed up trying to work on the fork, I have opened another PR to continue discussion in #619

**Pull request closed without merging**
